Fix compilation on WASM (#794)
Disable loop unrolling for `Fp::into_bigint` that led to WASM
miscompilations with too many local variables:

```
Error: failed to deserialize wasm module

Caused by:
    0: failed to parse code section
    1: locals exceed maximum (at offset 16977)
```

Issue diagnosed by @paberr and @ii-cruz.

Fixes #615.

Co-authored-by: Pratyush Mishra <pratyushmishra@berkeley.edu>